### ISSUE TITLE
Error in tests/run_test.py

### ISSUE THREAD

**Issue by say2sankalp** [donnemartin/haxor-news#132]
I just ran the master and got this

```
python tests/run_tests.py 
...................F.E........................................................
======================================================================
ERROR: test_load_hiring_and_freelance_ids_invalid_url (test_config.ConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sankalp/Dev/haxor-news/tests/test_config.py", line 60, in test_load_hiring_and_freelance_ids_invalid_url
    os.remove('./downloaded_settings.py')
FileNotFoundError: [Errno 2] No such file or directory: './downloaded_settings.py'

======================================================================
FAIL: test_load_hiring_and_freelance_ids (test_config.ConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sankalp/Dev/haxor-news/tests/test_config.py", line 53, in test_load_hiring_and_freelance_ids
    assert self.hn.config.hiring_id != who_is_hiring_post_id
AssertionError

----------------------------------------------------------------------
Ran 76 tests in 7.678s

FAILED (failures=1, errors=1)

```
I need a good eye to understand whats wrong here!!

**Comment by donnemartin** [comment]
@say2sankalp I think this is related to https://github.com/donnemartin/haxor-news/issues/129 where these tests require internet.

**Comment by say2sankalp** [comment]
@donnemartin  yeah, I got it fixed, brought a modification little. Life is so busy, I get less time for beloved git.

**Comment by donnemartin** [comment]
This should now be fixed with https://github.com/donnemartin/haxor-news/pull/177.
