### ISSUE TITLE
Fatal error on start

### ISSUE THREAD

**Issue by binaryplease** [donnemartin/haxor-news#174]
Installed from AUR on arch linux, everything up-to-date as of 2019-03-17
The program doesn't start, but displays this error

```

✱ haxor-news
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 2.0.8 (/usr/lib/python3.7/site-packages), Requirement.parse('prompt-toolkit<1.1.0,>=1.0.0'), {'haxor-news'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/haxor-news", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prompt-toolkit<1.1.0,>=1.0.0' distribution was not found and is required by haxor-news


```

**Comment by donnemartin** [comment]
Hi @binaryplease, you have a higher version of prompt toolkit than currently supported.  Support for version 2.0+ is dependent on https://github.com/donnemartin/haxor-news/pull/118.
