### ISSUE TITLE
Error "wrong color format 'reverse'"

### ISSUE THREAD

**Issue by AntouanK** [donnemartin/haxor-news#88]
Installed `haxor-news` today on Arch.
I get this error
```
8:36:35 antouank@i7 ~ haxor-news
Traceback (most recent call last):
  File "/usr/bin/haxor-news", line 11, in <module>
    load_entry_point('haxor-news==0.4.1', 'console_scripts', 'haxor-news')()
  File "/usr/lib/python3.6/site-packages/haxor_news/main.py", line 25, in cli
    haxor = Haxor()
  File "/usr/lib/python3.6/site-packages/haxor_news/haxor.py", line 110, in __init__
    self._create_cli()
  File "/usr/lib/python3.6/site-packages/haxor_news/haxor.py", line 153, in _create_cli
    style_factory = StyleFactory(self.theme)
  File "/usr/lib/python3.6/site-packages/haxor_news/style.py", line 31, in __init__
    self.style = self.style_factory(name)
  File "/usr/lib/python3.6/site-packages/haxor_news/style.py", line 49, in style_factory
    class CliStyle(Style):
  File "/usr/lib/python3.6/site-packages/pygments/style.py", line 101, in __new__
    ndef[0] = colorformat(styledef)
  File "/usr/lib/python3.6/site-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'reverse'
```

**Comment by donnemartin** [comment]
Hi @AntouanK, thanks for the report!  Can you paste the output of:

    $ pip freeze

I suspect your `pygments` version might be causing the issue.

**Comment by AntouanK** [comment]
@donnemartin Sorry for the late response.
`pip` is not an available command. Sorry, I'm not a python user.
Should I install pip somehow?

**Comment by AntouanK** [comment]
```
19:07:04 antouank@i7 ~ pip freeze
appdirs==1.4.2
Beaker==1.8.1
cached-property==1.3.0
chardet==2.3.0
click==6.7
colorama==0.3.7
cupshelpers==1.0
docker==2.1.0
docker-compose==1.11.2
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
haxor-news==0.4.1
isc==2.0
jsonschema==2.6.0
louis==3.0.0
Mako==1.0.6
MarkupSafe==0.23
packaging==16.8
prompt-toolkit==1.0.13
psutil==5.1.3
pycups==1.9.73
pycurl==7.43.0
Pygments==2.2.0
pygobject==3.22.0
pyparsing==2.1.10
pyxdg==0.25
PyYAML==3.12
Reflector==2017.1.7.0.23.12
requests==2.13.0
simplejson==3.10.0
six==1.10.0
team==1.0
termcolor==1.1.0
texttable==0.8.7
urllib3==1.20
wcwidth==0.1.7
websocket-client==0.40.0
youtube-dl==2017.3.6
```

**Comment by troyready** [comment]
FWIW, I'm also affected by this, seems to be occurring on new installs on multiple platforms (Mac OS 10.12 & Ubuntu 16.10)

**Comment by vegeterrixen** [comment]
I'm also have this error. my machine OS X 10.11.6 with Python 3.6.0.
What i've found to get haxor-news working again is to install prompt_toolkit-0.52-py3.
This error occurred in my machine after installed IPython, which is use prompt_toolkit-1.0.13-py3.

**Comment by troyready** [comment]
Thanks for identifying that -- that was the issue for me as well. Moving to a virtualenv works around the issue.

**Comment by donnemartin** [comment]
Hi Everyone, thanks for the helping tracking this down!

I hope to update to prompt-toolkit 1.0.0+ soon with https://github.com/donnemartin/haxor-news/issues/71.

**Comment by donnemartin** [comment]
Fixed in https://github.com/donnemartin/haxor-news/pull/94 with the update to prompt-toolkit 1.0.0+.
